In [ ]:
# Persiapan membuat data
import pandas as pd
import random

pelajaran = ['Matematika', 'Fisika', 'Biologi', 'Kimia', 'Geologi', 'Ekonomi']
kelas = ['12A', '12B', '12C', '12D']

hasil_nilai = {
    'siswa_id' : range(1, 21),
    'pelajaran' : [random.choice(pelajaran) for i in range(20)],
    'nilai' : [random.choice(range(0, 100)) for i in range(20)],
    'jenis-kelamin' : [random.choice(['laki-laki', 'perempuan']) for i in range(20)],
    'kelas' : [random.choice(kelas) for i in range(20)]
}

df = pd.DataFrame(hasil_nilai)
print(df)

    siswa_id   pelajaran  nilai jenis-kelamin kelas
0          1     Biologi     52     laki-laki   12C
1          2     Ekonomi     81     laki-laki   12A
2          3      Fisika     36     perempuan   12B
3          4       Kimia     60     laki-laki   12B
4          5     Ekonomi      3     perempuan   12C
5          6       Kimia     58     laki-laki   12D
6          7       Kimia     89     laki-laki   12B
7          8       Kimia     87     laki-laki   12D
8          9     Ekonomi     81     laki-laki   12C
9         10      Fisika     64     perempuan   12C
10        11     Ekonomi     76     perempuan   12C
11        12     Ekonomi     96     laki-laki   12C
12        13  Matematika     90     perempuan   12B
13        14       Kimia     62     perempuan   12D
14        15  Matematika     22     laki-laki   12A
15        16     Biologi     82     laki-laki   12D
16        17  Matematika     49     perempuan   12D
17        18      Fisika     81     laki-laki   12B
18        19  Matematika     52     perempuan   12A
19        20  Matematika     55     perempuan   12C

<h2>Soal 1: Indexing</h2>

1. Lakukan indexing terhadap dataframe untuk mengakses column nilai dan kelas saja
2. Lakukan indexing terhadap dataframe untuk mengakses row 5 sampai 10 beserta column pelajaran dan nilai

In [ ]:
# code here
a = df[['nilai', 'kelas']]
print(a)
c = df.iloc[5:11, 1:3]
print(c)

    nilai kelas
0      52   12C
1      81   12A
2      36   12B
3      60   12B
4       3   12C
5      58   12D
6      89   12B
7      87   12D
8      81   12C
9      64   12C
10     76   12C
11     96   12C
12     90   12B
13     62   12D
14     22   12A
15     82   12D
16     49   12D
17     81   12B
18     52   12A
19     55   12C
   pelajaran  nilai
5      Kimia     58
6      Kimia     89
7      Kimia     87
8    Ekonomi     81
9     Fisika     64
10   Ekonomi     76

<h2>Soal 2: Filter DataFrame Dengan Boolean</h2>

1. Tampilkan semua data siswa pada mata pelajaran Ekonomi dan Fisika
2. Tampilkan semua data siswa yang mempunyai nilai lebih dari 50 di mata pelajaran Kimia 
3. Tampilkan semua data yang mempunyai nilai lebih dari 70, berjnis kelamin perempuan dan di kelas 12C

In [ ]:
# code here
satu = df.loc[(df['pelajaran'] == 'Ekonomi') | (df['pelajaran'] == 'Fisika')]
print(satu)
dua = df.loc[(df['pelajaran'] == 'Kimia') & (df['nilai'] > 50)]
print(dua)
tiga = df.loc[(df['nilai'] > 70) & (df['jenis-kelamin'] == 'perempuan') & (df['kelas'] == '12C')]
print(tiga)

    siswa_id pelajaran  nilai jenis-kelamin kelas
1          2   Ekonomi     81     laki-laki   12A
2          3    Fisika     36     perempuan   12B
4          5   Ekonomi      3     perempuan   12C
8          9   Ekonomi     81     laki-laki   12C
9         10    Fisika     64     perempuan   12C
10        11   Ekonomi     76     perempuan   12C
11        12   Ekonomi     96     laki-laki   12C
17        18    Fisika     81     laki-laki   12B
    siswa_id pelajaran  nilai jenis-kelamin kelas
3          4     Kimia     60     laki-laki   12B
5          6     Kimia     58     laki-laki   12D
6          7     Kimia     89     laki-laki   12B
7          8     Kimia     87     laki-laki   12D
13        14     Kimia     62     perempuan   12D
    siswa_id pelajaran  nilai jenis-kelamin kelas
10        11   Ekonomi     76     perempuan   12C

<h2>Soal 3: Data Transformation</h2>

lakukan data transformasi terhadap column 'nilai' dengan fungsi transformasi, berikut rumus dari normalisasi

![alt text](https://drive.google.com/uc?id=1wed-EbRSTA0JP1ceDp6lcKBqH2yJ4aa3)

In [ ]:
# code here
def normalized(df) :
  return (df - df.min()) / (df.max() - df.min())
print(df[['nilai']].apply(normalized))

       nilai
0   0.526882
1   0.838710
2   0.354839
3   0.612903
4   0.000000
5   0.591398
6   0.924731
7   0.903226
8   0.838710
9   0.655914
10  0.784946
11  1.000000
12  0.935484
13  0.634409
14  0.204301
15  0.849462
16  0.494624
17  0.838710
18  0.526882
19  0.559140